<a href="https://colab.research.google.com/github/dataneto/Estudos/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
O Numpy é uma bliblioteca para realizar operações numeriacas em python. 

* Ela suporta operações complexas envolvendo vetores e matrizes, sendo muito simplis e performatico de se resolver

In [ ]:
#Importando a biblioteca
import numpy as np 

In [ ]:
#Criando um array de 1 dimensão
uma_dim = np.array([1, 2, 3, 4, 5])

#Mostrando o arrey criado
uma_dim

array([1, 2, 3, 4, 5])

In [ ]:
#Mostrando o tipo do objeto
type(uma_dim)

numpy.ndarray

In [ ]:
#Mostrando as dimençoes do arrey
uma_dim.ndim

1

In [ ]:
#Criando um outro arrey com mais dimensões
duas_dim = np.array([(1, 2, 3), (4, 5, 6)])

In [ ]:
#Mostrando o arrey criado
duas_dim

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [ ]:
#Mostrando as dimençoes do arrey
duas_dim.ndim

2

In [ ]:
#Criando um array (de 5 linhas e 2 dimensões) com números aleatórios
np.random.random((5,2))

array([[0.13155075, 0.42269006],
       [0.27326818, 0.29992758],
       [0.60780976, 0.46155119],
       [0.66318675, 0.07540074],
       [0.37785063, 0.85793564]])

In [ ]:
#Criando um array com valores iniciando do 10 até o 50, com intervalo de 5 em 5
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Criando um array linear de 0 a 2 com no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
#Criando um array(3x4) nulo (de valores zero).
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Arrays Vs Listas

- Arrays permitem fazer operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos (int, float, str, bool)
- Arrays considera todos os elementos de tipos distintos como str


In [ ]:
#Criando uma lista em Python.
lista = [1,2,3]

In [ ]:
#Mostrando a lista
lista

[1, 2, 3]

In [ ]:
#Multiplicando os valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

    note que a lista foi duplicada, e não seus elementos

In [ ]:
#Transformando a variável lista em um array Numpy
lista = np.array(lista)

In [ ]:
#Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [ ]:
#Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

    Agora podemos ver que, em array, os elementos foram multiplicados por 2

### Calculadora de IMC

In [ ]:
#Calcular IMC de pessoas.
pesos = [67,81,120,90] #Adicionando uma lista com pesos
alturas = [1.68,1.70,1.75,1.85] #Adicionando uma lista com valores

In [ ]:
#Fazendo o calculo usando as listas
pesos / altura ** 2

TypeError: ignored

    ele deu erro pois dividimos os valores de uma lista por outra, o que não é permitido no python

In [ ]:
#Transformando as listas em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
#Calculando o IMC pelos arrays
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [ ]:
#Arrays Numpy armazenam elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [ ]:
#mostando o array
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

    podemos ver que todos viraram str

In [ ]:
#Multiplicando por 2
a * 2 

UFuncTypeError: ignored

    não conseguiremos multiplicar pois os valores são str [dtype('<U21')]

## Métodos e Atributos Úteis

In [ ]:
#Métodos disponíveis (digite o . pressione tab).
duas_dim.

In [ ]:
#Monstrando o array
duas_dim

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [ ]:
#Retorna a forma do array no formato linhas e colunas.
duas_dim.shape

(2, 3)

In [ ]:
#Quantidade de dimensões.
duas_dim.ndim

2

In [ ]:
#Imprimindo o valor máximo do array.
uma_dim.max()

5

In [ ]:
# Imprimindo o valor mínimo.
uma_dim.min()

1

In [ ]:
# Imprimindo o valor médio.
uma_dim.mean()

3.0

In [ ]:
#Imprimindo o desvio padrão.
duas_dim.std()

1.707825127659933

In [ ]:
#mostrando o tipo dos dados
duas_dim.dtype

dtype('int64')

In [ ]:
#Mostrando a quantidade de elementos que tem no array
duas_dim.size

6

In [ ]:
#Mostrando a quantidade de itens em bytes
duas_dim.itemsize

8

In [ ]:
#Somando todos os elementos do array
duas_dim.sum()

21

## Transformando Arrays

In [ ]:
#Gerando a transposta da Matriz (Linha -> coluna)
duas_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Transforma em uma matriz de uma linha.
duas_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Criando um array de três dimensões, com numeros aleatorios
tres_dim = np.random.random((5,3))

In [ ]:
#verificando a dimensão
tres_dim.shape

(5, 3)

In [ ]:
#Exibindo o array
tres_dim

array([[0.9491954 , 0.56117938, 0.7561909 ],
       [0.87497656, 0.1832262 , 0.96508686],
       [0.94764482, 0.56817549, 0.35983136],
       [0.84694315, 0.56128374, 0.07651149],
       [0.03217788, 0.42399357, 0.9518778 ]])

In [ ]:
#Transformando em uma matriz com 3 linhas e 5 colunas
tres_dim.reshape(3,5)

array([[0.9491954 , 0.56117938, 0.7561909 , 0.87497656, 0.1832262 ],
       [0.96508686, 0.94764482, 0.56817549, 0.35983136, 0.84694315],
       [0.56128374, 0.07651149, 0.03217788, 0.42399357, 0.9518778 ]])

In [ ]:
#Transformando em uma matriz de linha unica
tres_dim.reshape(-1)

array([0.9491954 , 0.56117938, 0.7561909 , 0.87497656, 0.1832262 ,
       0.96508686, 0.94764482, 0.56817549, 0.35983136, 0.84694315,
       0.56128374, 0.07651149, 0.03217788, 0.42399357, 0.9518778 ])

In [ ]:
#Criando uma variavel para armazenar um array de uma linha e 15 colunas
t = tres_dim.reshape(1,15)
t

array([[0.9491954 , 0.56117938, 0.7561909 , 0.87497656, 0.1832262 ,
        0.96508686, 0.94764482, 0.56817549, 0.35983136, 0.84694315,
        0.56128374, 0.07651149, 0.03217788, 0.42399357, 0.9518778 ]])

In [ ]:
#Adicionando elementos a um array, 10 na posição 0.
duas_dim = np.insert(duas_dim,0,10)

In [ ]:
duas_dim

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
#Apagando o elemento da primeira posição do array.
duas_dim = np.delete(duas_dim,[0])

In [ ]:
duas_dim

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",duas_dim, delimiter=',')